Proktor.Crawler/Projektor.WebApp/Controllers/HealthController.cs
using Microsoft.AspNetCore.Mvc;
using Projektor.Core;
using System.Linq;
using System.Threading;

namespace Projektor.WebApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class HealthController : ControllerBase
    {
        private readonly Engine _engine;

        public HealthController(Engine engine)
        {
            _engine = engine;
        }

        [HttpGet]
        public IActionResult OnGet(CancellationToken token)
        {
            return new JsonResult(_engine.Projects.Count());
        }
    }
}

Proktor.Crawler/Projektor.WebApp/Pages/Components/TdUl/Default.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Projektor.WebApp.Pages.Components.TdUl
{
    public class DefaultModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Proktor.Crawler/Projektor.WebApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Projektor.Core;
using Projektor.Core.Models;

namespace Projektor.WebApp.Pages
{
    public class IndexModel : PageModel
    {
        public readonly Engine Engine;
        [BindProperty(SupportsGet = true)]
        public int Pagination { get; set; }
        public bool IsEngineSearching => Engine.IsSearching;
        public string TimeRemaining
        {
            get
            {
                var time = Engine.RemainingTimeUntilCrawlingIsStartedAgain;
                if (time == TimeSpan.MaxValue) return "Suche wurde nicht gestartet.";
                //ToDo Remove hours, because was added for docker container
                var text = $"Eine neue Suche findet um {DateTime.Now.Add(time).AddHours(2).ToString("HH:mm:ss")} statt.";
                return text;
            }
        }

        public string SearchTitle
        {
            get
            {
                var title = $"Suche {(IsEngineSearching ? "läuft" : "abgeschlossen")}";
                return title;
            }
        }
        public IEnumerable<Project> Projects => ProjectsOnPagePage(Pagination);
        public bool HasProjects => Projects.Any();
        public bool IsEngineStarted => Engine.IsStarted;
        public bool HasNextPage => ProjectsOnPagePage(Pagination + 1).Any();
        public bool HasPreviousPage => ProjectsOnPagePage(Pagination - 1).Any() && Pagination > 0;
        public string SearchText
        {
            get
            {
                var text = IsEngineSearching
                    ? "Bitte laden Sie ab und zu die Seite neu, um die aktuellsten Projekte zu erhalten."
                    : TimeRemaining;
                return text;
            }
        }

        public IndexModel(Engine engine)
        {
            Engine = engine;
        }

        public async Task<IActionResult> OnPostStartEngine(CancellationToken token)
        {
            if (!Engine.IsStarted) Engine.Start();
            await Task.Delay(4000, token);
            return RedirectToPage("Index");
        }

        public IActionResult OnPostStopEngine(CancellationToken token)
        {
            Engine.Stop();
            return RedirectToPage("Index");
        }
        private IEnumerable<Project> ProjectsOnPagePage(int pageNumber)
        {
            var projectsToDisplay = 10;
            var projectsToSkip = projectsToDisplay * pageNumber;
            var projects = Engine.Projects.Skip(projectsToSkip).Take(projectsToDisplay);
            return projects;
        }
    }
}

Proktor.Crawler/Projektor.WebApp/Pages/Projects.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Projektor.Core;
using Projektor.Core.Models;

namespace Projektor.WebApp.Pages
{
    public class ProjectsModel : PageModel
    {
        public List<Project> Projects { get; }
        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }
        public bool ShowProject => Id > -1;
        public Project Project => Projects[Id];
        public ProjectsModel(Engine engine)
        {
            Id = -1;
            Projects = engine.Projects.ToList();
        }
        public void OnGet()
        {
            
        }
    }
}

Proktor.Crawler/Projektor.WebApp/ViewComponents/ProjectCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Projektor.Core.Models;
using System.Threading.Tasks;

namespace Projektor.WebApp.ViewComponents
{
    public class ProjectCardViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(Project project)
        {
            return Task.FromResult((IViewComponentResult)View(project));
        }
    }
}

Proktor.Crawler/Projektor.WebApp/ViewComponents/TdUlViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Projektor.WebApp.Pages.Components.TdUl;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Projektor.WebApp.ViewComponents
{
    public class TdUlViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(IEnumerable<string> source)
        {
            return Task.FromResult((IViewComponentResult)View(new TdUlModel(source)));
        }
    }
}

Proktor.Crawler/Projektor.WebApp/Pages/Components/ProjectCard/Default.cshtml
@model Projektor.Core.Models.Project

<div class="eight wide column divide">
    <div class="ui grid attached border-orange">
        <div class="sixteen wide column">
            <div class="ui center aligned large header">
                @Model.Title
            </div>
        </div>
        <div class="eight wide column">
            <div class="ui center aligned large header">
                <div class="ui horizontal divider">
                    <div class="ui header medium">Details</div>
                </div>
            </div>
            <p>Ort : @Model.Location</p>
            <p>Referenznummer : @Model.ReferenceNumber</p>
            <p>Start : @Model.StartingDate</p>
            <p>Dauer : @Model.Duration</p>
            <p>Position : @Model.Position</p>
        </div>
        <div class="eight wide column">
            <div class="ui center aligned large header">
                <div class="ui horizontal divider">
                    <div class="ui header medium">Aufgaben</div>
                </div>
            </div>
            <div class="ui bulleted list">
                @foreach (var task in Model.Tasks)
                {
                    <div class="item">@task</div>
                }
            </div>
        </div>
        <div class="eight wide column">
            <div class="ui horizontal divider">
                <div class="ui header medium">Qualifikationen</div>
            </div>
            <div class="ui bulleted list">
                @foreach (var qualification in Model.Qualifications)
                {
                    <div class="item">@qualification</div>
                }
            </div>
        </div>
        <div class="eight wide column">
            <div class="ui horizontal divider">
                <div class="ui header medium">Einsatzinformationen</div>
            </div>
            <div class="ui bulleted list">
                @foreach (var information in Model.EmploymentInformation)
                {
                    <div class="item">@information</div>
                }
            </div>
        </div>
        <div class="sixteen wide center aligned attached column">
            @if (Model.HasContact)
            {
                <div class="ui horizontal divider">
                    <div class="ui header medium">Kontakt</div>
                </div>
                @if (Model.HasAnsprechpartner)
                {
                    <div class="ui center aligned header">Ansprechpartner(in) : @Model.Contact.Name</div>
                }
                @if (Model.HasTelephoneNumber)
                {
                    <a class="ui green label large" href="@Model.Contact.TelephoneNumber">
                        <i class="phone icon"></i>@Model.Contact.TelephoneNumber
                    </a>
                }
                @if (Model.HasEmailNumber)
                {
                    <a class="ui green label large" href="@Model.Contact.Email">
                        <i class="mail icon"></i> @Model.Contact.Email
                    </a>
                }
            }
            <div class="ui hidden divider"></div>
            <a class="bottom-attached" href="@Model.Uri.OriginalString" target="_blank">
                <div class="ui horizontal divider"><i class="globe icon"></i>   Zum Projekt</div>
            </a>
        </div>
    </div>
</div>

Proktor.Crawler/Projektor.WebApp/Pages/Components/TdUl/Default.cshtml
@model Projektor.WebApp.Pages.Components.TdUl.TdUlModel

<td>
    <ul>
        @foreach (var value in Model.Values)
        {
        <li>@value</li>
        }
    </ul>
</td>

Proktor.Crawler/Projektor.WebApp/Pages/Index.cshtml
@page "/{pagination?}"
@model Projektor.WebApp.Pages.IndexModel
@{
    Layout = "_Layout";
}
<div class="ui section horizontal divider">
    <div class="ui large center aligned header">Aktionen</div>
</div>
@if (Model.IsEngineStarted)
{
    <div class="ui icon message">
        <i class="notched circle loading icon"></i>
        <div class="content">
            <div class="header">
                @Model.SearchTitle
            </div>
            <p>@Model.SearchText</p>
        </div>
    </div>
    <form method="post">
        <button class="ui button negative" asp-page-handler="StopEngine">Suche stoppen</button>
    </form>
}
else
{
    <form method="post">
        <button class="ui button positive" asp-page-handler="StartEngine">Suche starten</button>
    </form>
}
@if (!Model.HasProjects)
{
    <div class="ui message">
        <div class="header">
            Keine Projekte vorhanden.
        </div>
        <p>Haben Sie schon versucht, den Suchvorgang zu starten?</p>
    </div>
}
else
{
    <div class="ui section horizontal divider"><div class="ui large center aligned header">Projekte</div></div>
    <div class="ui grid">
        @foreach (var project in Model.Projects)
        {
            <vc:project-card project="project"></vc:project-card>
        }
    </div>
}
<div class="ui section horizontal divider">
    <div class="ui large center aligned header">Navigation</div>
</div>
<div class="ui grid">
    <div class="row">
        <div class="sixteen wide column">
            @if (Model.HasPreviousPage)
            {
                <form method="post">
                    <a class="ui left floated button" href="/@(Model.Pagination - 1)">Vorherige Seite</a>
                </form>
            }
            @if (Model.HasNextPage)
            {
                <form method="post">
                    <a class="ui right floated button" href="/@(Model.Pagination + 1)">Nächste Seite</a>
                </form>
            }
        </div>
    </div>
</div>

Proktor.Crawler/Projektor.WebApp/Pages/Projects.cshtml
@page "{id?}"
@model Projektor.WebApp.Pages.ProjectsModel
@{
    Layout = "_Layout";
}

<div class="ui grid">
    <div class="four wide column">
        <div class="ui vertical fluid tabular menu">
            @for (var i = 0; i < Model.Projects.Count; i++)
            {
                var project = Model.Projects[i];
                <div class="item">
                    <i class="ui icon sync alternate"></i>
                    <div class="content">
                        <a class="header" asp-page="Projects" asp-route-id="@i">@project.Title</a>
                    </div>
                </div>
            }
        </div>
    </div>
    @if (Model.ShowProject)
    {
        <div class="twelve wide column">
            <vc:project-card project="@Model.Project"></vc:project-card>
        </div>
    }
</div>

Proktor.Crawler/Projektor.WebApp/Pages/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="~/lib/semantic-ui/semantic.min.css" rel="stylesheet" />
    <link href="~/css/SemanticExtension.css" rel="stylesheet" />
</head>
<body>
    <div class="ui grid">
        <div class="two wide column">
            <div class="ui vertical fluid tabular menu">                
                <div class="item">
                    <i class="ui icon sync alternate"></i>
                    <div class="content">
                        <a class="header" asp-page="Index">Status</a>
                    </div>
                </div>
                <div class="item">
                    <i class="ui icon calendar outline"></i>
                    <div class="content">
                        <a class="header" asp-page="Projects">Projekte</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="fourteen wide column">
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/semantic-ui/semantic.min.js"></script>
    <script src="~/js/SemanticSettings.js"></script>
</body>
</html>